<?xml version="1.0"?>
<package format="3">
  <name>couchmo_bringup</name>
  <version>0.1.0</version>
  <description>Top-level launch and bringup for Couchmo</description>
  <maintainer email="you@example.com">Couchmo Team</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>couchmo_description</exec_depend>
  <exec_depend>couchmo_nav</exec_depend>
  <exec_depend>nav2_bringup</exec_depend>
  <exec_depend>slam_toolbox</exec_depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
